# Generated by Django 3.1.4 on 2021-12-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(blank=True, max_length=100, null=True, verbose_name='ポジショングループ')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(blank=True, null=True, verbose_name='リリース日')),
                ('initial', models.IntegerField(blank=True, null=True, verbose_name='初期総合値')),
                ('maximum', models.IntegerField(blank=True, null=True, verbose_name='最大総合値')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='最大レベル')),
                ('player_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='選手名')),
                ('position_category', models.CharField(blank=True, choices=[('0', 'CF'), ('1', 'ST'), ('2', 'LWG'), ('3', 'RWG'), ('4', 'LMF'), ('5', 'RMF'), ('6', 'OMF'), ('7', 'CMF'), ('8', 'DMF'), ('9', 'LSB'), ('10', 'RSB'), ('11', 'CB'), ('12', 'GK')], max_length=2, verbose_name='ポジション')),
                ('league_category', models.CharField(blank=True, choices=[('0', 'イングランドリーグ'), ('1', 'スペインリーグ'), ('2', 'Serie A TIM'), ('3', 'Ligue 1 Uber Eats'), ('4', 'Liga NOS'), ('5', 'Süper Lig'), ('6', 'Tinkoff Russian Premier Liga'), ('7', 'Eredivisie'), ('8', 'Scottish Premiership'), ('9', 'その他(ヨーロッパ)')], max_length=2, verbose_name='所属リーグ')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='国名')),
                ('club', models.CharField(blank=True, max_length=30, null=True, verbose_name='所属クラブ')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身長')),
                ('dominant_foot', models.CharField(blank=True, max_length=2, null=True, verbose_name='利き足')),
                ('playstyle', models.CharField(blank=True, max_length=30, null=True, verbose_name='プレースタイル')),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プレイヤー画像')),
                ('club_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.clubcategory', verbose_name='クラブグループ')),
            ],
        ),
        migrations.CreateModel(
            name='PositionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='ポジショングループ')),
            ],
        ),
        migrations.CreateModel(
            name='RarityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(blank=True, max_length=100, null=True, verbose_name='レアリティ')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_skill', models.CharField(blank=True, max_length=20, null=True, verbose_name='スキル入力')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.positioncategory', verbose_name='ポジショングループ'),
        ),
        migrations.AddField(
            model_name='player',
            name='rarity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.raritycategory', verbose_name='レアリティ'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_images', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='フォーメーション画像')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_sense', models.IntegerField(blank=True, null=True, verbose_name='OFセンス')),
                ('ball_control', models.IntegerField(blank=True, null=True, verbose_name='ボールコントロール')),
                ('dribble', models.IntegerField(blank=True, null=True, verbose_name='ドリブル')),
                ('ball_keep', models.IntegerField(blank=True, null=True, verbose_name='ボールキープ')),
                ('grander_pass', models.IntegerField(blank=True, null=True, verbose_name='グランダーパス')),
                ('fly_pass', models.IntegerField(blank=True, null=True, verbose_name='フライパス')),
                ('determining_power', models.IntegerField(blank=True, null=True, verbose_name='決定力')),
                ('heading', models.IntegerField(blank=True, null=True, verbose_name='ヘディング')),
                ('place_kick', models.IntegerField(blank=True, null=True, verbose_name='プレースキック')),
                ('curve', models.IntegerField(blank=True, null=True, verbose_name='カーブ')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='スピード')),
                ('instantaneous_power', models.IntegerField(blank=True, null=True, verbose_name='瞬発力')),
                ('kick_power', models.IntegerField(blank=True, null=True, verbose_name='キック力')),
                ('jumping', models.IntegerField(blank=True, null=True, verbose_name='ジャンプ')),
                ('physical_contact', models.IntegerField(blank=True, null=True, verbose_name='フィジカルコンタクト')),
                ('body_control', models.IntegerField(blank=True, null=True, verbose_name='ボディコントロール')),
                ('physical_fitness', models.IntegerField(blank=True, null=True, verbose_name='体力')),
                ('defense_sense', models.IntegerField(blank=True, null=True, verbose_name='ディフェンスセンス')),
                ('take_the_ball', models.IntegerField(blank=True, null=True, verbose_name='ボール奪取')),
                ('aggressiveness', models.IntegerField(blank=True, null=True, verbose_name='アグレッシブネス')),
                ('gksense', models.IntegerField(blank=True, null=True, verbose_name='GKセンス')),
                ('catching', models.IntegerField(blank=True, null=True, verbose_name='キャッチング')),
                ('clearing', models.IntegerField(blank=True, null=True, verbose_name='クリアリング')),
                ('cobraging', models.IntegerField(blank=True, null=True, verbose_name='コブラシング')),
                ('deflectiveing', models.IntegerField(blank=True, null=True, verbose_name='ディフレクティング')),
                ('reverse_foot_frequency', models.IntegerField(blank=True, null=True, verbose_name='逆足頻度')),
                ('reverse_foot_accuracy', models.IntegerField(blank=True, null=True, verbose_name='逆足精度')),
                ('condition_stability', models.IntegerField(blank=True, null=True, verbose_name='コンディション安定度')),
                ('injury_resistance', models.IntegerField(blank=True, null=True, verbose_name='ケガ耐性')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
    ]
