# Generated by Django 3.1.4 on 2021-12-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(blank=True, max_length=100, null=True, verbose_name='ポジショングループ')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league_category',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_category',
        ),
        migrations.AddField(
            model_name='player',
            name='league_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.leaguecategory', verbose_name='クラブグループ'),
            preserve_default=False,
        ),
    ]
