# Generated by Django 3.1.4 on 2021-12-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211229_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcategory',
            name='clubname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='クラブグループ'),
        ),
        migrations.AlterField(
            model_name='leaguecategory',
            name='leaguename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='リーググループ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='league_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.leaguecategory', verbose_name='リーググループ'),
        ),
    ]
