# Generated by Django 3.1.4 on 2021-12-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211229_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='skill',
            field=models.ManyToManyField(blank=True, to='mainapp.Skill', verbose_name='スキル'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.player', verbose_name='紐づき選手'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.player', verbose_name='紐づき選手'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='player_skill',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='スキル名'),
        ),
    ]
