# Generated by Django 3.1.4 on 2021-12-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211230_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStyleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playstyle', models.CharField(blank=True, max_length=30, null=True, verbose_name='プレースタイルグループ')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='playstyle',
        ),
        migrations.AddField(
            model_name='player',
            name='playstyle_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.playstylecategory', verbose_name='プレースタイルグループ'),
            preserve_default=False,
        ),
    ]
