# Generated by Django 3.1.4 on 2022-01-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_player_new_date_field'),
    ]

    operations = [
    ]
