# Generated by Django 3.1.4 on 2022-01-26 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220127_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='new_date_field',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 26, 15, 39, 39, 740050, tzinfo=utc), null=True, verbose_name='リリース日'),
        ),
    ]
