# Generated by Django 3.1.4 on 2022-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20220127_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='new_date_field',
            field=models.DateTimeField(blank=True, null=True, verbose_name='リリース日'),
        ),
    ]
