# Generated by Django 3.1.4 on 2022-02-07 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_player_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='リリース日'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.clubcategory', verbose_name='クラブグループ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='league_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.leaguecategory', verbose_name='リーググループ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playstyle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.playstylecategory', verbose_name='プレースタイルグループ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.positioncategory', verbose_name='ポジショングループ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rarity_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.raritycategory', verbose_name='レアリティ'),
        ),
    ]
