# Generated by Django 3.1.4 on 2022-02-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220207_2118'),
    ]

    operations = [
    ]
