# Generated by Django 3.1.4 on 2022-02-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220207_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='new_date_field',
        ),
        migrations.AddField(
            model_name='clubcategory',
            name='league_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.leaguecategory', verbose_name='リーググループ'),
        ),
    ]
