# Generated by Django 3.1.4 on 2022-02-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20220213_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcategory',
            name='league_group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.leaguecategory', verbose_name='リーググループ'),
        ),
    ]
