# Generated by Django 3.1.4 on 2022-05-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20220504_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='グレードレベル')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='grade_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.gradecategory', verbose_name='グレードグループ'),
        ),
    ]
