# Generated by Django 3.1.4 on 2022-05-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20220504_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_correction', models.IntegerField(blank=True, null=True, verbose_name='ポジション')),
                ('short_counter_correction', models.IntegerField(blank=True, null=True, verbose_name='ショートカウンター')),
                ('long_counter_correction', models.IntegerField(blank=True, null=True, verbose_name='ロングカウンター')),
                ('side_attack_correction', models.IntegerField(blank=True, null=True, verbose_name='サイドアタック')),
                ('long_ball_correction', models.IntegerField(blank=True, null=True, verbose_name='ロングボール')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.player', verbose_name='紐づき選手')),
            ],
        ),
    ]
