# Generated by Django 3.1.4 on 2022-05-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_playercorrection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='maximum',
        ),
    ]
