# Generated by Django 3.1.4 on 2022-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_remove_player_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='defensive_consciousness',
            field=models.IntegerField(blank=True, null=True, verbose_name='守備意識'),
        ),
    ]
