# Generated by Django 3.1.4 on 2022-08-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_colorcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwg_opacity', models.IntegerField(blank=True, null=True, verbose_name='LWG透明度')),
                ('cf_opacity', models.IntegerField(blank=True, null=True, verbose_name='CF透明度')),
                ('st_opacity', models.IntegerField(blank=True, null=True, verbose_name='ST透明度')),
                ('rwg_opacity', models.IntegerField(blank=True, null=True, verbose_name='RWG透明度')),
                ('lmf_opacity', models.IntegerField(blank=True, null=True, verbose_name='LMF透明度')),
                ('omf_opacity', models.IntegerField(blank=True, null=True, verbose_name='OMF透明度')),
                ('cmf_opacity', models.IntegerField(blank=True, null=True, verbose_name='CMF透明度')),
                ('dmf_opacity', models.IntegerField(blank=True, null=True, verbose_name='DMF透明度')),
                ('rmf_opacity', models.IntegerField(blank=True, null=True, verbose_name='RMF透明度')),
                ('lsb_opacity', models.IntegerField(blank=True, null=True, verbose_name='LSB透明度')),
                ('cb_opacity', models.IntegerField(blank=True, null=True, verbose_name='CB透明度')),
                ('rsb_opacity', models.IntegerField(blank=True, null=True, verbose_name='RSB透明度')),
                ('gk_opacity', models.IntegerField(blank=True, null=True, verbose_name='GK透明度')),
                ('cb_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cb_position', to='mainapp.colorcategory', verbose_name='CBポジションカラー')),
                ('cf_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cf_position', to='mainapp.colorcategory', verbose_name='CFポジションカラー')),
                ('cmf_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmf_position', to='mainapp.colorcategory', verbose_name='CMFポジションカラー')),
                ('dmf_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dmf_position', to='mainapp.colorcategory', verbose_name='DMFポジションカラー')),
                ('gk_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gk_position', to='mainapp.colorcategory', verbose_name='GKポジションカラー')),
                ('lmf_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lmf_position', to='mainapp.colorcategory', verbose_name='LMFポジションカラー')),
                ('lsb_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lsb_position', to='mainapp.colorcategory', verbose_name='LSBポジションカラー')),
                ('lwg_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lwg_position', to='mainapp.colorcategory', verbose_name='LWGポジションカラー')),
                ('omf_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='omf_position', to='mainapp.colorcategory', verbose_name='OMFポジションカラー')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.player', verbose_name='紐づき選手')),
                ('rmf_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rmf_position', to='mainapp.colorcategory', verbose_name='RMFポジションカラー')),
                ('rsb_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rsb_position', to='mainapp.colorcategory', verbose_name='RSBポジションカラー')),
                ('rwg_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rwg_position', to='mainapp.colorcategory', verbose_name='RWGポジションカラー')),
                ('st_position_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='st_position', to='mainapp.colorcategory', verbose_name='STポジションカラー')),
            ],
        ),
    ]
