# Generated by Django 3.1.4 on 2022-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_formationcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationcolor',
            name='cb_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='CB透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='cf_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='CF透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='cmf_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='CMF透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='dmf_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='DMF透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='gk_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='GK透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='lmf_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='LMF透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='lsb_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='LSB透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='lwg_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='LWG透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='omf_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='OMF透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='rmf_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='RMF透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='rsb_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='RSB透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='rwg_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='RWG透明度'),
        ),
        migrations.AlterField(
            model_name='formationcolor',
            name='st_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='ST透明度'),
        ),
    ]
