# Generated by Django 3.1.4 on 2022-09-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20220831_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
