# Generated by Django 3.1.4 on 2021-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.TextField(blank=True, default='', verbose_name='自己紹介'),
        ),
    ]
